### ISSUE TITLE
Please upload to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [nest-desktop/nest-desktop-AppImage#1]
Hello, thanks for making an AppImage. We'd like to feature it on appimage.github.io.

However, it is not good practice to check large binary files (such as AppImages) into git repositories. Instead, the AppImage should be uploaded to GitHub Releases:
https://github.com/nest-desktop/nest-desktop-AppImage/releases

If you do this, then we can re-run our test at
https://github.com/AppImage/appimage.github.io/pull/2643

Thank you very much.

**Comment by babsey** [comment]
Ok, I understand now and always upload AppImages for releases.
